### ISSUE TITLE
`go get github.com/p4tin/goaws` stopped working

### ISSUE THREAD

**Issue by giorgiosironi** [p4tin/goaws#102]
At some point in the last months, the command in the Readme started giving this error on new machines:
```
$ go version
go version go1.2.1 linux/amd64
$ sudo GOPATH=/usr/local/src go get github.com/p4tin/goaws                                  
package github.com/p4tin/goaws
        imports github.com/p4tin/goaws
        imports github.com/p4tin/goaws: no buildable Go source files in /usr/local/src/src/github.com/p4tin/goaws
```
To work around this, I now do:
```
            go get -d github.com/p4tin/goaws
            cd /usr/local/src/github.com/p4tin/goaws
            git checkout 941608ca3f63bdace571268a241d6835002edd94
            go get github.com/p4tin/goaws
```
as that commit was one that got installed on existing machines. This sequence correctly compiles and installs a `goaws` binary.

**Comment by p4tin** [comment]
After a bit of re-structuring the build command should now be:  `go build app/cmd/goaws.go`, give that a try.  Also I see you are using go 1.2.1, I suggest upgrading since we are at go 1.8 now and I am only supporting 2 versions back so go 1.6+.
