### ISSUE TITLE
Implement platform specific raw message delivery

### ISSUE THREAD

**Issue by gpsamson** [p4tin/goaws#103]
SNS allows you to set platform specific data in the message body like so:
```
{
    "default":  "I am the default message.",
    "sqs": "I am the message that if raw delivery is enabled"
}
```

Currently, `goaws` doesn't handle platform specific data. Will be opening a fork to work on this, but also wanted to open an issue for more discussion.

**Comment by p4tin** [comment]
@gpsamson any updates or questions on how to implement this?

**Comment by p4tin** [comment]
@gpsamson any movement on this - no one else has asked for it - I will close this in the next few days if you are no longer interested.
