### ISSUE TITLE
Readme build instructions not working

### ISSUE THREAD

**Issue by dllewellyn** [p4tin/goaws#107]
The instructions to build & to "go get .." command give the error "Can't load package .": No buildable go files in (path). Can't figure out a way around this

**Comment by p4tin** [comment]
try this:

- go get github.com/p4tin/goaws/...
- cd $GOPATH/src/github.com/p4tin/goaws
- go build -o goaws app/cmd/goaws.go

That should have create a 'goaws' executable in the current directory that you can then move somewhere in your path.

**Comment by p4tin** [comment]
README updated!!!
