### ISSUE TITLE
SNS subscribe(topicArn, sqsArn) is duplicating subscriptions

### ISSUE THREAD

**Issue by cotko** [p4tin/goaws#112]
Just like queues and topics do not duplicate if you call the `CreateQueue`/`CreateTopic` with the same name multiple times, the `Subscribe(topicArn, queueArn)` does not duplicate the subscription when using same topicArn and queueArn pair on actual aws, while goaws does not work like expected, it keeps adding the subscriptions.

This can be tested using the postman collection from the readme, executing the *Subscribe* multiple times and then checking the result of *ListSubscriptions* will show that there are multiple subscriptions with same topic/queue pairs.

**Comment by brianmoran** [comment]
@cotko - PR submitted https://github.com/p4tin/goaws/pull/113

**Comment by p4tin** [comment]
PR merged
