### ISSUE TITLE
As a GoAWS Docker user, I would like to pass AWS related information as parameter so I can use GoAWS together with other local AWS services, such as Local DynamoDB

### ISSUE THREAD

**Issue by danielpsf** [p4tin/goaws#115]
I'm currently using a local [DynamoDB Docker](https://github.com/instructure/dynamo-local-admin-docker) which supports the parameters below and as many of us do use SNS/SQS within other AWS services, would be nice to have these options so we could use GoAWS with other AWS local services.

`-e AWS_ACCESS_KEY_ID=key -e AWS_SECRET_ACCESS_KEY=secret aws --region us-east-1 dynamodb --endpoint http://localhost:8000/
`

**Comment by p4tin** [comment]
@danielpsf I apologize but I am not exactly sure what you are asking for me to implement.  Can you give me a bit more detail on what the goaws code would do with the extra parameters...

**Comment by danielpsf** [comment]
Hi @p4tin,

I would like to have all my local environment with the same parameters, such as AWS credentials and region, so I can start other AWS local components like DynamoDB or Kinesis and yet have the same configuration.
So, if you implement a parameter like AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY or AWS_REGION we could easily achieve a local complex environment setup with a couple of docker runs.

What do you think?

**Comment by p4tin** [comment]
Sorry again I am still confused... Are those docker parameters?  or do you want goaws to accept ENVIRONMENT VARIABLES instead of using the config.yaml?

**Comment by danielpsf** [comment]
Well, they can be docker parameters, but it also would be alright to use the config.yaml to configure the **AWS_ACCESS_KEY**, **AWS_SECRET_KEY** and **AWS_REGION**. I haven't noticed it on https://github.com/p4tin/goaws/blob/master/app/conf/goaws.yaml (which I think is the config model).

As you've shown [here](https://github.com/p4tin/goaws/blob/bf331033dc819ff605dcaa6f70fbaa698013ec40/app/examples/java/SnsSample.java#L19) we've to use X/X to access the GoAWS service. What I'm saying is that it would be nice to have a way of set those details into the docker during start time, so we can develop within a larger ecosystem of applications that also require that kind of information.

I don't know if what I'm asking is already developed, I can be missing something that is already done and can solve this issue. If that is the case, sorry 😊.

**Comment by danielpsf** [comment]
Wow, nice... Thanks man :wink:
