### ISSUE TITLE
SQS Improper Return Code

### ISSUE THREAD

**Issue by bwaggone** [p4tin/goaws#118]
Hi, I found some behavior with sqs that doesn't perfectly match in the emulator.

Specifically, when attempting to create a queue, if you try and create another queue with the same name, it normally would just give a 200, since the queue has already been created. But if you try and create a queue with the same name and a different retention period, on the GUI it shows this:

![image](https://user-images.githubusercontent.com/6710311/31618470-07100006-b260-11e7-96b2-aad06c8e701c.png)

And on the command line, aws gives back a 400 in this case. goaws returns a 200 regardless.

**Comment by p4tin** [comment]
@bwaggone  that's because currently the create queue does not accept any options - it simply creates the queue with the default 30 secs visibility timeout.  I do plan on adding more functionnality later to make this work then the response code will mimic AWS/SQS.
