### ISSUE TITLE
Concurrent map access exception on startup

### ISSUE THREAD

**Issue by OSeraph** [p4tin/goaws#122]

**Comment by brianmoran** [comment]
@OSeraph Can you provide more context on the issue and/or supply the full error?

**Comment by brianmoran** [comment]
I do not get the same results on `master` branch

<img width="1209" alt="screen shot 2017-12-05 at 6 22 15 pm" src="https://user-images.githubusercontent.com/5261397/33636242-5c3dede4-d9e9-11e7-9964-41b7dbc04f54.png">
