### ISSUE TITLE
QueueArn is not a correctly formed ARN

### ISSUE THREAD

**Issue by clicktravel-steffan** [p4tin/goaws#127]
Using goaws, I can create an example queue and view its attributes. It appears the `QueueArn` is given the same value as the queue's URL, which is incorrect behaviour.

A correctly formed ARN for a SQS queue should be of the form
```arn:aws:sqs:<region>:<account-id>:<queuename>```
See https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-sqs

Example:
```
$ aws --endpoint-url http://localhost:4100 sqs create-queue --queue-name example

{
    "QueueUrl": "http://localhost:4100/queue/example"
}

$ aws --endpoint-url http://localhost:4100 sqs get-queue-attributes --queue-url http://localhost:4100/queue/example

{
    "Attributes": {
        "ApproximateNumberOfMessagesNotVisible": "0", 
        "LastModifiedTimestamp": "0000000000", 
        "CreatedTimestamp": "0000000000", 
        "ApproximateNumberOfMessages": "0", 
        "ReceiveMessageWaitTimeSeconds": "0", 
        "DelaySeconds": "0", 
        "VisibilityTimeout": "30", 
        "QueueArn": "http://localhost:4100/queue/example"
    }
}
```
In this example, I would expect `QueueArn` to instead have value `arn:aws:sqs:local:000000000000:example`

**Comment by p4tin** [comment]
Fixed in version 1.0.1 - docker image 1.0.1
