### ISSUE TITLE
Cannot start Docker container on Linux

### ISSUE THREAD

**Issue by soenkenils** [p4tin/goaws#131]
I'm trying to run the `goaws` container (version: `latest`) on an EC2 instance like this:
```
docker run --rm -it -p 4100:4100 --name sqs -v $PWD/goaws.yml:/goaws.yml pafortin/goaws -config /goaws.yml
```

And I get the following error message:
```
standard_init_linux.go:185: exec user process caused "exec format error"
```

**Comment by jeff-blaisdell** [comment]
+1  We're having the same issue.  Had been running the beta version with success for sometime, but there isn't a tag for it to fall back on.

**Comment by bstraightiff** [comment]
Same.

**Comment by jeff-blaisdell** [comment]
fwiw, while folks wait for the above fix, I pushed a work around image here:

https://hub.docker.com/r/jeffblaisdell/goaws

Based off of:
https://github.com/p4tin/goaws/commit/4e5c34c302e49f95017c116a75e17541b9c337db

**Comment by p4tin** [comment]
Appears to be working now...  Can you guys try it again please - I just re-push version 1.0.1 again

thanks!

[root@vultr ~]# docker pull pafortin/goaws
Using default tag: latest
latest: Pulling from pafortin/goaws
2fdfe1cd78c2: Pull complete
b40483a921cd: Pull complete
05a54504c344: Pull complete
Digest: sha256:e7849640fc1996fd030ea8e9e0105cfa63fa985361cfb7cc6d2561a658428b62
Status: Downloaded newer image for pafortin/goaws:latest
[root@vultr ~]# docker run --rm -it -p 4100:4100 --name sqs -v $PWD/goaws.yml:/goaws.yml pafortin/goaws -config /goaws.yml
{"level":"warning","msg":"Loading config file: /goaws.yml","time":"2018-01-23T02:25:53Z"}
{"level":"warning","msg":"GoAws listening on: 0.0.0.0:4100","time":"2018-01-23T02:25:53Z"}

**Comment by giorgiosironi** [comment]
I appreciate the quick response, but it was a bit confusing to see the `1.0.1` tag being updated. I would suggest in these cases to push a `1.0.2` and delete `1.0.1` to keep immutability of releases (not now since people have already updated to solve the problem). Thanks again for resolving the issue.

**Comment by jeff-blaisdell** [comment]
Works again for us!  Thanks for quick turn around.
