### ISSUE TITLE
Include goaws binaries with releases

### ISSUE THREAD

**Issue by jonsie** [p4tin/goaws#133]
Can you include goaws binaries with each release?  Something like this:

https://github.com/spinnaker/roer/releases

That way we can just add the binary and necessary configs to our own Docker images.  Thanks!

**Comment by p4tin** [comment]
good suggestion - I'll be doing that over the weekend

**Comment by p4tin** [comment]
@jonsie - there is now a `bin.tar.gz` in the release that encompasses all the binaries.
