### ISSUE TITLE
SQS subscriptions to SNS topics can't be specified by queue ARN

### ISSUE THREAD

**Issue by jbrechtel** [p4tin/goaws#140]
It seems like SNS->SQS subscriptions can only be created by `queue URL` instead of `queue ARN`.

Specifically for the subscription I create to work with goaws then I must specify the `queue URL` as the endpoint but the AWS CLI docs say that the `queue ARN` must be the endpoint value for an SQS subscription.

Here is a gist with scripts demonstrating creating a subscription each way. Notably the one that creates a subscription by `queue ARN` never receives the message.

https://gist.github.com/jbrechtel/e21dc3a5a5d5b0c78231f4bd1f96601a

**Comment by iambbs** [comment]
This issue prevents from subscribing using any AWS Client. I am starting to work on solution now
