### ISSUE TITLE
Request: Implement SendMessageBatch

### ISSUE THREAD

**Issue by zachschultz** [p4tin/goaws#141]
Hi there! First off, thanks for making this, it is integrating extremely nicely with my existing local Lambda docker development setup.

I was scratching my head for a while trying to figure out why `send-message-batch` wouldn't work, when I realized that it wasn't implemented. Do you have any plans to implement that function soon? I would try but I don't have much, if any, experience with Go.

**Comment by p4tin** [comment]
Thanks for the kind words - I have add SendMessageBatch on the radar for a while (see Issue #74).  I will try to get to it in the next week or so.

**Comment by p4tin** [comment]
Complete and merged in PR #142

**Comment by rg1220** [comment]
@p4tin  - Can you update the docker image with this update?
