### ISSUE TITLE
receive request with  WaitTimeSeconds causes goaws to stop responding

### ISSUE THREAD

**Issue by archa347** [p4tin/goaws#147]
It seems like using the `WaitTimeSeconds` parameter on a receive request causes the request to hang and `goaws` to stop responding to all further requests.

I was able to reproduce this with `goaws`, with the example config, using the Node AWS SDK in this script

```
const AWS = require('aws-sdk');
const SQS = new AWS.SQS({
    endpoint : 'http://localhost:4100',
    region: 'local-01',
    accessKeyId: 'my key',
    secretAccessKey: 'my secret'
});

const params = {
    QueueUrl: 'http://localhost:4100/queue/local-queue1',
    MessageAttributeNames: ['All'],
    WaitTimeSeconds: 1
};

SQS.receiveMessage(params)
    .on('success', (resp) => console.log(JSON.stringify(resp.data)))
    .on('error', (error) => console.log(error))
    .send();
```

I also observed this initially with the Java AWS SDK.  It seems to happen even if there is a message waiting on the queue.

**Comment by nhoughto** [comment]
Any workaround / movement on this? its pretty limiting..

**Comment by p4tin** [comment]
I tried to duplicate but I am not using nodeJS here is a postman showing the results note the 2 sec wait time and the result time is just over 2 secs.

![image](https://user-images.githubusercontent.com/7197804/66745770-eac23780-ee4d-11e9-9758-60cbcaa4993e.png)
