### ISSUE TITLE
Logstash SNS Output to goaws SNS topic in Docker

### ISSUE THREAD

**Issue by jcksnvllxr80** [p4tin/goaws#162]
I have docker running goaws and i added a separate container running a python daemon that i wrote. The python daemon reads from the SQS endpoint i have subscribed to my SNS topic and does a POST to a webapp in another docker container running tomcat. All of this works perfectly in one docker-compose.yml. I can publish a message directly to my goaws SNS topic using the python publish API and i recieve the output in elasticsearch which is after my webapp. I view the elasticsearch cluster in Kibana (yet another container I have running). 

I wanted to take things a step further and add Logstash to the stack in docker. I cant get logstash SNS output plugin to send a messsage to the goaws SNS topic. It wants to send it to sns.us-east-1.amazonaws.com which I dont have credentials for. Do you have any idea what is causing this issue?

**Comment by p4tin** [comment]
@jcksnvllxr80 I am not sure but I imagine that this is a logstash limitation (or there could be an 'endpoint' configuration for the logstash plugin?
