### ISSUE TITLE
RedrivePolicy not readed from yaml configuration

### ISSUE THREAD

**Issue by LuisPiedra** [p4tin/goaws#166]
Being able to pre configure the queues in goaws.yaml is very handy, but it seems it's not working for Redrive Policy attributes. I have tried different combinations but it would not reach queue configuration on startup:

`RedrivePolicy:
    MaxReceiveCount: 4
    DeadLetterTargetArn: "arn:aws:sqs::000000000000:failed-messages"`

`RedrivePolicy: '{"maxReceiveCount": "4", "deadLetterTargetArn":"arn:aws:sqs::000000000000:failed-messages"}'`

`RedrivePolicy:
    maxReceiveCount: 4
    deadLetterTargetArn: "arn:aws:sqs::000000000000:failed-messages"`

**Comment by bvisness** [comment]
Yeah, looks like the config loader just doesn't support redrive policies at all. There are no references to it in the source code. I would think that all settable queue attributes should be supported in this config file so I don't have to actually run a CLI command _after_ using a config file!
