### ISSUE TITLE
Persisting data

### ISSUE THREAD

**Issue by mozey** [p4tin/goaws#169]
Please excuse me if this has been discussed before, but I could not find anything related. Are there any plans to make data persistent when running the docker version?

Maybe a `-snapshot path/to/file.json` param, this can be used to specify queue messages must be serialized to disk when the container is stopped, and it can be used for initialization when it is started?

**Comment by p4tin** [comment]
As a developer tool, I never imagined a reason to save messages in a queue to disk or any other media.  Can you provide me a use case please?

**Comment by mozey** [comment]
I would use it for a couple of things
- if my application expects queues to already exist, I could create them, make a snapshot and set it to recreate the queues when the container is started
- setup of queues and mock messages for integration testing, the serialized test data might be stored in a repos
- sniff the content of messages created by an unfamiliar application for analysis

I could also do all of the above by writing some scripts, maybe using the [aws cli](https://aws.amazon.com/cli) tool, that is then executed before or after the container starts. Just thought it could be useful if this was built in

**Comment by p4tin** [comment]
The first point can already be done with the JSON configuration file, as far as 2 and 3 I like it...  Did you intend on submitting a PR for this?

**Comment by mozey** [comment]
> can already be done with the JSON configuration file

Thanks, I missed that you can specify queues in the [config file](https://github.com/p4tin/goaws/blob/master/app/conf/goaws.yaml)

> Did you intend on submitting a PR for this?

I can look into it, wanted to find out if I'm missing something that already exists. And I'm not sure what would be an appropriate format for the serialized data. [Local DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) uses one or more SQLite db files for persisting data

**Comment by p4tin** [comment]
If your intent is `sniff the content of messages created by an unfamiliar application for analysis` then storing the data in a SQL DB type storage like Dynamo or SQLite might prove to be cumbersome - I'd suggest a JSON array in a file for each queue (by queueName) that way you can also restore queues without the help of the config but you might be missing other configs on those queues like subscriptions, etc,..  I'll be looking forward to the PR and don't hesitate to ask any questions you might have.
