### ISSUE TITLE
Add Support For Posting To Subscription Endpoint Over HTTP/S

### ISSUE THREAD

**Issue by conatus** [p4tin/goaws#173]
Thanks for your work on this library.

For the purposes of writing end to end tests, we'd love it if the SNS publish method actually pushed out a HTTP/S endpoint if the subscription had `http` set as its protocol. I can see it already does this for the faked SQS service. https://github.com/p4tin/goaws/blob/master/app/gosns/gosns.go#L305-L346

So the task would be something like:

- [ ] Move the SQS subscription logic into its own private method to prevent `Publish` from becoming unwieldy.
- [ ] Add support for checking its a valid protocol for a subscription to https://github.com/p4tin/goaws/blob/master/app/gosns/gosns.go#L71-L108
- [ ] Work out the exact way in which HTTP endpoints are hit - the headers involved, the payload, either from documentation or experimentation.
- [ ] Add a method to `Publish` which pushes out a SNS message to the endpoint and handles errors using a private method.
- [ ] Tests and so on.

Happy to try to add this feature but wanted to make this issue before I do just in case you had thought on the implementation or believe this is something out of scope for this application.

**Comment by p4tin** [comment]
I like this enhancement I have add a change request open for a while but have not looked into implemented it yet (change #75) but i am happy to entertain a pull request for this functionnality

**Comment by p4tin** [comment]
This was implemented under PR #175
