### ISSUE TITLE
Wrong path and port when adding a new queue

### ISSUE THREAD

**Issue by Jerome1337** [p4tin/goaws#177]
I'm trying to create a new queue using

    aws --endpoint-url http://localhost:4100 sqs create-queue  --queue-name test1

But the result is 

    {
        "QueueUrl": "http://:/queue/test1"
    }

The path and port conbinaise looks wrong. This look not good. I'm just using the Docker image and added `awscli` to the goaws container.

Did I miss something  or this is a new bugs ?

**Comment by p4tin** [comment]
I do not install the awscli inside the container.  The container exposes port 4100 so you can use it from outside the container which gives me the correct results.  Can you try that?

`
--> aws --endpoint-url http://localhost:4100 sqs list-queues
{
    "QueueUrls": [
        ...
    ]
}
--> aws --endpoint-url http://localhost:4100 sqs create-queue --queue-name test1
{
    "QueueUrl": "http://localhost:4100/queue/test1"
}
--> aws --endpoint-url http://localhost:4100 sqs list-queues
{
    "QueueUrls": [
        ...
        "http://localhost:4100/queue/test1", 
        ...
    ]
}
`

**Comment by Jerome1337** [comment]
Ok this is working !

Thanks.
