### ISSUE TITLE
Add travis step to auto create a release in github and auto publish to DockerHub from master

### ISSUE THREAD

**Issue by jairovadillo** [p4tin/goaws#182]
Just an enhancement but would be nice: https://ops.tips/blog/travis-ci-push-docker-image/

I can try to do it myself in a few days :D

**Comment by p4tin** [comment]
This ticket should do 2 things when a commit to master happens:

1.  A new release is created in github (including all binaries - listed below), and;
1. Push a new docker images to dockerhub.

**Comment by p4tin** [comment]
I am now usign goreleaser, homebrew and github actions so hopefully all will be smooth
