### ISSUE TITLE
Log file not written in 1.1.2

### ISSUE THREAD

**Issue by dpiddockcmp** [p4tin/goaws#197]
Commit https://github.com/p4tin/goaws/commit/8d635c3b676f0c0c92ed0c86f70ee7256a877ac7 removed the use of the log file. This wasn't mentioned as part of the PR or release notes.

Please could the log file be restored? The config loading code wasn't modified and the example configs still imply the log file is used.

If removing the log file was intentional please:
- emit warnings when `LogFile` or `LogMessages: true` in the config file so that users are aware of the change
- give more flexibility in selecting output log level. `debug` is too noisy and the default of `warning` does not display messages.
- remove variables from sample configs

**Comment by p4tin** [comment]
Fixed in v0.2.2
