### ISSUE TITLE
Connection Timeout with Sqs Receive message

### ISSUE THREAD

**Issue by skrajath** [p4tin/goaws#224]
I tried your example code. But I get Connectiontimeout error.

> https://github.com/p4tin/goaws/blob/master/app/examples/java/SqsSample.java

`Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to us-east-1.goaws.com:4100 [us-east-1.goaws.com/208.118.245.121] failed: connect timed out
`
`Caused by: java.net.SocketTimeoutException: connect timed out
`

Not sure, whats wrong here. No other changes are made to example.  Is there any other configuration i am missing here?

**Comment by p4tin** [comment]
I'm not sure why you got that error but it seems like a networking issue on your end.  How did you run goaws in docker or native (and what about the sample command line?

**Comment by DayS1eeper** [comment]
You've tried to connect to `goaws.com` host that is obviously not your local goaws server.

> [us-east-1.goaws.com/208.118.245.121] failed: connect timed out

```
host goaws.com
goaws.com has address 208.118.245.121
```
