### ISSUE TITLE
Config file requires queues, topics to exist and have at least one entry

### ISSUE THREAD

**Issue by zfeinberg-urbn** [p4tin/GoAws#46]
When no queues or topics are added such as 
  Queues:
  Topics:

or if those are left out entirely, goaws doesn't load the settings from the config file

**Comment by p4tin** [comment]
After testing here it seems to work fine both ways:

1.
Local:
  Host: localhost
  Port: 4100
  LogMessages: true
  LogFile: ./goaws_messages.log
  Queues:
  Topics:
2.
Local:
  Host: localhost
  Port: 4100
  LogMessages: true
  LogFile: ./goaws_messages.log


Note make sure there is a <CR> at the end of the last line
