### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by amc6** [p4tin/goaws#71]
When I run `go get github.com/p4tin/GoAws`

I get the following error:
```
can't load package: package github.com/p4tin/GoAws: case-insensitive import collision: "github.com/p4tin/GoAws/vendor/github.com/gorilla/context" and "github.com/p4tin/goaws/vendor/github.com/gorilla/context"
```

I'm on a mac and I assume this has something to do with the fact that the filesystem is case insensitive. Using `go get github.com/p4tin/goaws` seemed to fix it.

**Comment by p4tin** [comment]
ya I think I sould probably rename the project to "goaws" and that would fix this issue.  thanks!
