### ISSUE TITLE
Implement create-topic

### ISSUE THREAD

**Issue by tmornini** [p4tin/goaws#72]
So far, this meets nearly all of my needs to a completely local development environment.

Thank you!

If you implement create-topic, it will then satisfy my needs to test everything, including infrastructure setup, locally.

I'm building our go chops now. We may implement this as a PR once we have confidence to do so.

**Comment by p4tin** [comment]
Create topic is actually implemented see the postman collection to use it.

**Comment by tmornini** [comment]
Oh, I see, great!

I guess I was confused by the README.md:

```
(Topics are created hard coded (until create-topic is implemented)

aws --endpoint-url http://localhost:4100 sns list-topics
    {
        "Topics": [
            {
                "TopicArn": "arn:aws:sns:local:000000000000:topic1"
            }, 
            {
                "TopicArn": "arn:aws:sns:local:000000000000:topic2"
            }
        ]
    }
```

Note: topic1 and topic2 do appear to still be hard-coded... :-)

**Comment by tmornini** [comment]
@p4tin Should I file another ticket for removing topic1 and topic2?

**Comment by p4tin** [comment]
the 2 topics (topic1 and topic 2) have been removed and the README shows a sample response from list-topics.  I have changed the README.md file in the hopes that this clears up the confusion.  Thanks again!
