### ISSUE TITLE
if QueueUrl is empty in request parameters, request fails

### ISSUE THREAD

**Issue by y-maksym** [p4tin/goaws#84]
I am using AWSSDK 2.3.55.2 for .Net Framework
I have connected to the goaws.exe via the next C# code:

> var request = new ReceiveMessageRequest
>             {
>                 QueueUrl = "http://localhost:4100/queue/test_queue",
>                 MaxNumberOfMessages = 5,
>                 WaitTimeSeconds = 0
>             };
> 
>             var amazonSqsConfig = new AmazonSQSConfig();
>             amazonSqsConfig.ServiceURL = "http://localhost.fiddler:4100";
> 
>             var amazonSqsClient = new AmazonSQSClient(new BasicAWSCredentials("x", "x"), amazonSqsConfig);
>             Debugger.Break();
>             ReceiveMessageResponse response = amazonSqsClient.ReceiveMessageAsync(request).Result;

As a result, in the response I am expecting to get messages that are already in the test_queue, but instead I am receiving the next error:

> {"The remote server returned an error: (400) Bad Request."}. Message: "The specified ueue does not exist for this wsdl version."

To figure out what happens and why I used fiddler to track the post request that AmazonSQSClient is sending. I figured out that AmazonSQSClient sends the next POST request:

> POST http://localhost:4100/queue/development_brandupdatesmessage_v0 HTTP/1.1
> User-Agent: aws-sdk-dotnet-45/2.3.55.2 .NET Runtime/4.0 .NET Framework/4.0 OS/6.2.9200.0 ClientAsync
> Content-Type: application/x-www-form-urlencoded; charset=utf-8
> host: localhost:4100
> X-Amz-Date: 20170209T084928Z
> X-Amz-Content-SHA256: 4fc28a78714c6b6ecd8bb88bcc81331e9d279dfe61f617b50574070e171cd4a5
> Authorization: AWS4-HMAC-SHA256 Credential=x/20170209/us-east-1/sqs/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=0abc1eb8930d27786ae49e60198124e80505ffabeb23335d9fb33e78aab877fd
> Content-Length: 80
> Connection: Keep-Alive
> 
> Action=ReceiveMessage&MaxNumberOfMessages=5&Version=2012-11-05&WaitTimeSeconds=0

As we can see here in the request body there is no QueueUrl parameter. It is now in the request Url: 

> POST http://localhost:4100/queue/development_brandupdatesmessage_v0 HTTP/1.1

The bug is that goaws cannot handle this situation. For aws it is not a problem. 
The fix would be if QueueUrl is not present in the request body, take it from the request url.

**Comment by p4tin** [comment]
I'll fix this sometime this week - or a PR would also be very appreciated!!

**Comment by p4tin** [comment]
Should work now - new docker container pushed to docker hub as well.
