### ISSUE TITLE
Installation instructions may need update

### ISSUE THREAD

**Issue by ZianVW** [p4tin/goaws#91]
When attempting to install the package per the instructions, I get an error:

```
ubuntu@ubuntu-xenial:~/go$ go get github.com/p4tin/goaws
package github.com/p4tin/goaws: no buildable Go source files in /home/ubuntu/go/src/github.com/p4tin/goaws
```

I have very little knowledge of Go, but it looks like it was caused by commit 69bc0b0ebdad036edf8facd57ebf60050c74b002, which removed all the .go files from the project root.

Perhaps the installation instructions need to be updated?

**Comment by p4tin** [comment]
Instead of a "go get", just clone the project and use the command: 'go run app/cmd/goaws.go' to run it in dev mode.  or else you can just use the docker image.
